#!/usr/bin/env bash
memcap=$(volcanica-pki | xxd -p | tr -d '\n')
echo $memcap | xxd -r -p | head -n1 > "$1".pub
echo $memcap | xxd -r -p | grep -v ed25519 > $1
chmod 600 $1
ssh-keygen -s $1 -h -I $1 $1.pub
ssh-keygen -L -f "$1"-cert.pub
b2sum "$1"-cert.pub
sha256sum "$1"-cert.pub
sha1sum "$1"-cert.pub
b2sum "$1".pub
sha256sum "$1".pub
sha1sum "$1".pub
